In [1]:
import numpy as np

In [2]:
ar = np.arange(3, 32)

In [3]:
ar

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [4]:
np.any
np.all
np.where

<function numpy.core.multiarray.where>

In [6]:
help(np.where)

Help on built-in function where in module numpy.core.multiarray:

where(...)
    where(condition, [x, y])
    
    Return elements, either from `x` or `y`, depending on `condition`.
    
    If only `condition` is given, return ``condition.nonzero()``.
    
    Parameters
    ----------
    condition : array_like, bool
        When True, yield `x`, otherwise yield `y`.
    x, y : array_like, optional
        Values from which to choose. `x` and `y` need to have the same
        shape as `condition`.
    
    Returns
    -------
    out : ndarray or tuple of ndarrays
        If both `x` and `y` are specified, the output array contains
        elements of `x` where `condition` is True, and elements from
        `y` elsewhere.
    
        If only `condition` is given, return the tuple
        ``condition.nonzero()``, the indices where `condition` is True.
    
    See Also
    --------
    nonzero, choose
    
    Notes
    -----
    If `x` and `y` are given and input arrays are 1-D, `wh

In [7]:
ar

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [8]:
np.where(ar < 10, 15, 18)

array([15, 15, 15, 15, 15, 15, 15, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
       18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18])

In [9]:
np.where(ar < 10, 15)

ValueError: either both or neither of x and y should be given

In [10]:
help(np.any)

Help on function any in module numpy.core.fromnumeric:

any(a, axis=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)
    Test whether any array element along a given axis evaluates to True.
    
    Returns single boolean unless `axis` is not ``None``
    
    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a logical OR reduction is performed.
        The default (`axis` = `None`) is to perform a logical OR over all
        the dimensions of the input array. `axis` may be negative, in
        which case it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a reduction is performed on multiple
        axes, instead of a single axis or all the axes as before.
    out : ndarray, optional
        Alternate output array in which to place the result.  It must have
        

In [11]:
np.any([0, 1, 1, 1, 0])

True

In [12]:
np.any([False, True, False, True, True])

True

In [13]:
np.any([[True, False], [True, False]])

True

In [15]:
np.any([[True, False], [True, False]], axis = 1) # rightmost column

array([ True,  True], dtype=bool)

In [17]:
np.any([[True, False], [True, False]], axis = 0)# leftmost row

array([ True, False], dtype=bool)

In [18]:
#np.all does and operation
np.all([[True, False], [True, False]])

False

In [19]:
np.all([[True, False], [True, False]], axis = 0)

array([ True, False], dtype=bool)

In [20]:
np.all([[True, False], [True, False]], axis = 1)

array([False, False], dtype=bool)

In [21]:
ar

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [23]:
ar.sum()#sums the whole array

493

In [26]:
dir(ar)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 

In [27]:
ar.max()

31

In [28]:
ar.min()

3

In [29]:
ar.cumsum()

array([  3,   7,  12,  18,  25,  33,  42,  52,  63,  75,  88, 102, 117,
       133, 150, 168, 187, 207, 228, 250, 273, 297, 322, 348, 375, 403,
       432, 462, 493], dtype=int32)

In [30]:
ar

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [31]:
ar.size

29

In [34]:
ar2 = np.arange(0, 12).reshape([3, 4]) # 3 rows and 4 columns

In [35]:
ar2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
ar2.sum()

66

In [37]:
#row-wise sum axis = 1 => rows
ar2.sum(axis=1)

array([ 6, 22, 38])

In [46]:
#column-wise sum axis 0 => column
ar2.sum(axis=0)

array([12, 15, 18, 21])

In [40]:
ar3 = np.arange(0, 12).reshape((2, 2, 3))# 3 dimension 

In [41]:
ar3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [43]:
ar3.sum(axis=0) # adds column like 0 +6, 3 + 9

array([[ 6,  8, 10],
       [12, 14, 16]])

In [44]:
ar3.sum(axis=1)

array([[ 3,  5,  7],
       [15, 17, 19]])

In [45]:
ar3.sum(axis=2)

array([[ 3, 12],
       [21, 30]])

In [47]:
ar4 = np.arange(0, 16).reshape(2, 2, 2, 2)

In [48]:
ar4

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [49]:
ar4.sum(axis=0)

array([[[ 8, 10],
        [12, 14]],

       [[16, 18],
        [20, 22]]])

In [50]:
ar4.sum(axis=1)

array([[[ 4,  6],
        [ 8, 10]],

       [[20, 22],
        [24, 26]]])

In [51]:
ar4.sum(axis=2)

array([[[ 2,  4],
        [10, 12]],

       [[18, 20],
        [26, 28]]])

In [52]:
ar5 = np.arange(0, 24).reshape(2, 3, 4)

In [53]:
ar5

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [54]:
ar5.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [55]:
ar5.sum(axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [56]:
ar5.sum(axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [57]:
ar6 = np.arange(0, 120).reshape(2, 3, 4, 5)

In [58]:
ar6

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])

In [59]:
ar6.sum(axis=0)

array([[[ 60,  62,  64,  66,  68],
        [ 70,  72,  74,  76,  78],
        [ 80,  82,  84,  86,  88],
        [ 90,  92,  94,  96,  98]],

       [[100, 102, 104, 106, 108],
        [110, 112, 114, 116, 118],
        [120, 122, 124, 126, 128],
        [130, 132, 134, 136, 138]],

       [[140, 142, 144, 146, 148],
        [150, 152, 154, 156, 158],
        [160, 162, 164, 166, 168],
        [170, 172, 174, 176, 178]]])

In [60]:
ar6.sum(axis=1)

array([[[ 60,  63,  66,  69,  72],
        [ 75,  78,  81,  84,  87],
        [ 90,  93,  96,  99, 102],
        [105, 108, 111, 114, 117]],

       [[240, 243, 246, 249, 252],
        [255, 258, 261, 264, 267],
        [270, 273, 276, 279, 282],
        [285, 288, 291, 294, 297]]])

In [61]:
ar6.sum(axis=1).shape

(2, 4, 5)

In [63]:
ar6.sum(axis=2)

array([[[ 30,  34,  38,  42,  46],
        [110, 114, 118, 122, 126],
        [190, 194, 198, 202, 206]],

       [[270, 274, 278, 282, 286],
        [350, 354, 358, 362, 366],
        [430, 434, 438, 442, 446]]])

In [65]:
ar6.sum(axis=3)# last axis 3 is a rowwise operation

array([[[ 10,  35,  60,  85],
        [110, 135, 160, 185],
        [210, 235, 260, 285]],

       [[310, 335, 360, 385],
        [410, 435, 460, 485],
        [510, 535, 560, 585]]])